### ISSUE TITLE
consultation on authorization related issues

### ISSUE THREAD

**Issue by ousc** [official-pikafish/Pikafish#36]
### Describe the issue

Dear project owner, I am developing a stand-alone web chess game recently, and it looks like this:

![untitile](https://user-images.githubusercontent.com/31619017/223606549-98880e4c-6a4b-48f3-b728-984126572683.gif)

It will be free and open source. If I use the webassembly version of pikafish in this project, whether I need some kind of authorization, or leave some copyright information in the application, I don't know much about this aspect.

### Expected behavior

No

### Steps to reproduce

No

### Operating system

All

### Pikafish version

Pikafish 2023-03-05

**Comment by PikaCat-OuO** [comment]
> It will be free and open source. 

Free means you can use Pikafish's net weights for everything, with no need for authorization :)

For open source, according to GPLv3, if you are using UCI protocol to communicate with the engine as a stand-alone addon part, your app can actually be closed source for sure. If it's added through a library (.dll .so) form or directly becomes a part of your code, then it needs to stay open source.
But since you are already open source then, according to GPLv3,  just bring the license with the engine, and everything will be fine :)

Thank you so much for your recent contribution to Pikafish, I truly appreciate your support for Pikafish.
![__DV$CCQJV_0VTYN12~CY1P](https://user-images.githubusercontent.com/73384062/223617725-b1a36ff6-930d-40ac-a33d-f6cab8447c36.gif)

**Comment by ousc** [comment]
Thanks for your explanation and reply, I understand😊
